// 01801_01900_buff.proto
// Buff相关消息 msgid 范围 1801-1900
syntax = "proto2";

package org.gof.demo.worldsrv.msg;

import "google/protobuf/descriptor.proto";
import "options.proto";
import "00000_00000_def.proto";

// ============================================================
// Buff相关消息
// ============================================================

// MsgID: 1802
// Buff添加
message SCBuffAdd {
  option (msgid) = 1802;
  optional int64 objId = 1;      // 单元Id
  optional DBuff buff = 2;       // Buff信息
}

// MsgID: 1803
// Buff更新（群发）
message SCBuffUpdate {
  option (msgid) = 1803;
  optional int64 objId = 1;      // 单元Id
  optional DBuff buff = 2;       // Buff信息
}

// MsgID: 1804
// Buff消失（群发）
message SCBuffDispel {
  option (msgid) = 1804;
  optional int64 objId = 1;        // 单元Id
  optional int32 sn = 2;           // 需要移出的buffSn
}

// MsgID: 1805
// 驱散Buff
message CSBuffDispelByHuman {
  option (msgid) = 1805;
  required int64 sn = 1;
}
