// 02901_03000_skill.proto
// 技能相关消息 msgid 范围 2901-3000
syntax = "proto2";

package org.gof.demo.worldsrv.msg;

import "google/protobuf/descriptor.proto";
import "options.proto";
import "00000_00000_def.proto";

// ============================================================
// 技能相关消息
// ============================================================

// MsgID: 2911
// 技能初始化
message CSSkillInit {
  option (msgid) = 2911;
}

// MsgID: 2912
// 技能初始化结果
message SCSkillInitResult {
  option (msgid) = 2912;
  repeated DSkill skills = 1;          // 已经习得的技能
  repeated DInborn inborns = 2;        // 已经装备的天赋
  repeated DSkill activeRelSkills = 3; // 已经激活的羁绊
  repeated DSkill relSkills = 4;       // 装备的羁绊技能
}

// MsgID: 2913
// 技能升级
message CSSkillLevelup {
  option (msgid) = 2913;
  required int32 skillSn = 1;      // 要升级的技能SN
}

// MsgID: 2914
// 技能升级结果
message SCSkillLevelupResult {
  option (msgid) = 2914;
  optional bool result = 1;
  optional DSkill skill = 2;
}

// MsgID: 2915
// 天赋升级
message CSInbornLevelup {
  option (msgid) = 2915;
  required int32 inbornSn = 1;     // 要升级的天赋
}

// MsgID: 2916
// 天赋升级结果
message SCInbornLevelupResult {
  option (msgid) = 2916;
  optional bool result = 1;
  optional DInborn inborn = 2;
}

// MsgID: 2917
// 切换天赋
message CSChangeInborn {
  option (msgid) = 2917;
  required int32 pos = 1;          // 天赋的位置
  required int32 inbornSn = 2;     // 要升级的天赋
}

// MsgID: 2918
// 切换天赋结果
message SCChangeInbornResult {
  option (msgid) = 2918;
  optional bool result = 1;
  optional DInborn inborn = 2;
}

// MsgID: 2923
// 添加关联技能
message CSAddRelSkill {
  option (msgid) = 2923;
  required int32 relSkillSn = 1;   // 装备某个羁绊技能
  required int32 pos = 2;          // 技能的位置
}

// MsgID: 2924
// 添加关联技能结果
message SCAddRelSkillResult {
  option (msgid) = 2924;
  optional DSkill relSkills = 1;   // 装备的羁绊技能
}

// MsgID: 2925
// 删除关联技能
message CSDelRelSkill {
  option (msgid) = 2925;
  required int32 relSkillSn = 1;   // 卸下某个羁绊技能
  required int32 pos = 2;          // 技能的位置
}

// MsgID: 2926
// 删除关联技能结果
message SCDelRelSkillResult {
  option (msgid) = 2926;
  optional DSkill relSkills = 1;  // 装备的羁绊技能
}
