// 03401_03500_competition.proto
// 竞技场相关消息 msgid 范围 3401-3500
syntax = "proto2";

package org.gof.demo.worldsrv.msg;

import "google/protobuf/descriptor.proto";
import "options.proto";
import "00000_00000_def.proto";

// ============================================================
// 竞技场相关消息
// ============================================================

// MsgID: 3401
// 进入竞技场
message CSCompetitionEnter {
  option (msgid) = 3401;
}

// MsgID: 3402
// 结束竞技场
message CSCompetitionEnd {
  option (msgid) = 3402;
}

// MsgID: 3403
// 竞技场结束
message SCCompetitionEnd {
  option (msgid) = 3403;
  required bool win = 1;
}

// MsgID: 3404
// 离开竞技场
message CSCompetitionLeave {
  option (msgid) = 3404;
}

// MsgID: 3405
// 刷新敌人
message CSRefreshEnemy {
  option (msgid) = 3405;
}

// MsgID: 3407
// 竞技场信息
message SCCompetitionInfo {
  option (msgid) = 3407;
  optional DHumanInfo enemy = 1;
}

// MsgID: 3408
// 重置CD
message CSResetCDTime {
  option (msgid) = 3408;
}

// MsgID: 3409
// 重置CD结果
message SCResetCDTime {
  option (msgid) = 3409;
  required bool success = 1;
}

// MsgID: 3410
// 打开排行榜
message CSOpenRank {
  option (msgid) = 3410;
  required int32 type = 1;
}

// MsgID: 3411
// 排行榜结果
message SCRankResult {
  option (msgid) = 3411;
  repeated int32 ranks = 1;
}

// MsgID: 3412
// 竞技场战斗日志
message CSCompetitionBattleLog {
  option (msgid) = 3412;
}

// MsgID: 3413
// 竞技场战斗日志
message SCCompetitionBattleLog {
  option (msgid) = 3413;
  repeated DBattleLog logs = 1;
}

// MsgID: 3414
// 刷新次数
message CSRefreshCount {
  option (msgid) = 3414;
  required int32 sn = 1;
}

// MsgID: 3415
// 刷新次数
message SCRefreshCount {
  option (msgid) = 3415;
  required int32 count = 1;
}

// MsgID: 3416
// 获取自己的排行榜页面
message CSGetSeflRankPage {
  option (msgid) = 3416;
  required int32 type = 1;
}

// MsgID: 3417
// 获取自己的排行榜页面
message SCGetSeflRankPage {
  option (msgid) = 3417;
  required int32 rank = 1;
}
